## Slicing

## 1-Dimension

In [17]:
import numpy as np

x = np.arange(10,20)
print( x )
print( x[1:5]) # Elements x[1] up to x[5] (excluded)
print( x[:4])  # all Elements  up to x[4] (excluded)
print( x[7:])  # all Elements following x[7] (included)
print( x[-4:-2])  

print (x[-4:-2].shape )



[10 11 12 13 14 15 16 17 18 19]
[11 12 13 14]
[10 11 12 13]
[17 18 19]
[16 17]
(2,)


## More Dimensions

In [20]:
x = np.arange(10,30).reshape(4,5)
print( x )
print("Nach Slicing:")
print(x[1:3,:])

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
[[15 16 17 18 19]
 [20 21 22 23 24]]


## Übungen

### Resaphe und Slicing

In [22]:
x = np.arange(0,10).reshape(2,5)
print( x )
print( x[1,3] )
print(x[:,1:3])

[[0 1 2 3 4]
 [5 6 7 8 9]]
8
[[1 2]
 [6 7]]


### np.arange mit drittem Parameter

In [24]:
x = np.arange(0,5,0.5)
print(x)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


### Summe von  Zufallszahlen 

In [26]:
x = np.random.uniform(10,20, size=(100000))
print( x.mean() )

15.000934898498661


In [70]:
mu = 0
sigma = 0.5
n = 100000
x = np.random.normal(mu, sigma, size=n )
print(x.sum())
print( np.sqrt(n))

-207.88496779378022
316.22776601683796
